spring:
  profiles:
    active: dev

server:
  port: 8082

headers:
  contentSecurityPolicy: "script-src 'self'"

userIPHeaderName: x-forwarded-for
#append a whitespace character at the end of prefix (before newline) if you want it to be separate from main message body
userIPLoggingPrefix: from IP
userIPLoggingMDCkey: userIP

h2:
  console:
    enabled: true

sqlms:
  saved-queries-dir: "./templates/"
  datasources:
    - name: test_db_1
      jdbcUrl: jdbc:h2:mem:test_db_1;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
      username: h2
      password: h2
      driverClassName: org.h2.Driver
logging:
  level:
    root: info
